# Generated by Django 5.0.2 on 2025-05-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
