# Generated by Django 5.0.2 on 2025-07-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_alter_registration_city_alter_registration_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='unique_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
